# Generated by Django 3.1.4 on 2020-12-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.IntegerField(choices=[(0, 'Kategorija'), (1, 'Doručak'), (2, 'Hladno predjelo'), (3, 'Toplo predjelo'), (4, 'Glavno jelo'), (5, 'Desert'), (6, 'Salate'), (7, 'Prilozi'), (8, 'Ostalo')], default=0, verbose_name='Kategorija'),
        ),
        migrations.CreateModel(
            name='BlogPostIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(blank=True, max_length=50, null=True)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
    ]
