# Generated by Django 3.1.4 on 2020-12-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201228_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='blogpostingredient',
            name='ingredient',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
