# Generated by Django 3.1.4 on 2020-12-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201228_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ingredient',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='step',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BlogPostIngredient',
        ),
    ]
