# Generated by Django 3.1.4 on 2020-12-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201229_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='step',
        ),
        migrations.CreateModel(
            name='BlogPostStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField(blank=True, max_length=500, null=True)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.TextField(blank=True, max_length=50, null=True)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
        ),
    ]
