# Generated by Django 3.1.4 on 2020-12-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201229_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpoststep',
            name='blogpost',
        ),
        migrations.DeleteModel(
            name='BlogPostIngredient',
        ),
        migrations.DeleteModel(
            name='BlogPostStep',
        ),
    ]
