# Generated by Django 3.1.4 on 2021-01-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210103_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
