# Generated by Django 3.1.4 on 2021-01-04 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210103_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
