# Generated by Django 3.1.4 on 2021-01-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210108_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
