# Generated by Django 3.1.4 on 2021-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_rating_post'),
        ('blog', '0015_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='rating',
            field=models.ManyToManyField(to='rating.Rating', verbose_name=''),
        ),
    ]
