# Generated by Django 3.1.4 on 2021-01-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_rating_post'),
        ('blog', '0016_blogpost_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='rating',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.rating'),
        ),
    ]
