# Generated by Django 3.1.4 on 2021-01-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_rating_post'),
        ('blog', '0017_auto_20210108_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='rating',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='rating',
            field=models.ManyToManyField(related_name='blog_posts', to='rating.Rating'),
        ),
    ]
