# Generated by Django 3.1.4 on 2021-01-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210108_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='rating',
        ),
    ]
